export const salons = [
  { id: 'estudio-norte', name: 'Estudio Norte', zone: 'Centro', km: 0.6, rating: 4.9, reviews: 312, price: 18, promo: '−20%', img: 'salon-1.jpg', cat: 'cut', services: [['Corte y lavado', 45, 18], ['Color completo', 120, 38], ['Perfilado de barba', 30, 10]] },
  { id: 'nail-lab', name: 'Nail Lab', zone: 'Chapinero', km: 1.2, rating: 4.7, reviews: 148, price: 15, img: 'nails.jpg', cat: 'nails', services: [['Manicura semipermanente', 60, 15], ['Diseño de uñas', 90, 24]] },
  { id: 'casa-olivo', name: 'Casa Olivo', zone: 'Laureles', km: 1.8, rating: 4.8, reviews: 201, price: 22, promo: '−30%', img: 'salon-2.jpg', cat: 'color', services: [['Balayage', 150, 55], ['Tratamiento capilar', 50, 22]] },
  { id: 'barberia-sur', name: 'Barbería Sur', zone: 'Poblado', km: 2.1, rating: 4.6, reviews: 97, price: 12, img: 'barber.jpg', cat: 'beard', services: [['Corte clásico', 40, 12], ['Barba y toalla caliente', 30, 10]] },
  { id: 'atelier-piel', name: 'Atelier Piel', zone: 'Usaquén', km: 2.6, rating: 4.9, reviews: 76, price: 30, img: 'detail.jpg', cat: 'skin', services: [['Limpieza facial', 60, 30], ['Masaje relajante', 50, 34]] },
];
export const cats = ['cut', 'nails', 'color', 'skin', 'beard'];
export const catIcon = { cut: 'corte', nails: 'unas', color: 'color', skin: 'piel', beard: 'barba' };
export const t = {
  es: { search: 'Corte, color, uñas…', sub: 'Cerca · Cualquier día', cut: 'Corte', nails: 'Uñas', color: 'Color', skin: 'Piel', beard: 'Barba', near: 'Cerca tuyo', book: 'Reservar turno', from: 'desde', services: 'Servicios', reviews: 'reseñas', like: 'Me gusta', pass: 'Pasar', empty: 'Viste todas las promos de hoy', home: 'Inicio', map: 'Mapa', appts: 'Turnos', favs: 'Favoritos', profile: 'Perfil', gateT: 'Ingresá para reservar', gateP: 'Podés explorar sin cuenta. Para reservar y pagar necesitamos saber quién sos. Ganás puntos en cada reserva.', gateB: 'Ingresar o crear cuenta', close: 'Seguir explorando', points: 'Ganás 40 puntos si reservás en Glowly', back: 'Volver' },
  en: { search: 'Cut, color, nails…', sub: 'Nearby · Any day', cut: 'Cut', nails: 'Nails', color: 'Color', skin: 'Skin', beard: 'Beard', near: 'Near you', book: 'Book appointment', from: 'from', services: 'Services', reviews: 'reviews', like: 'Like', pass: 'Pass', empty: "You've seen today's deals", home: 'Home', map: 'Map', appts: 'Bookings', favs: 'Saved', profile: 'Profile', gateT: 'Log in to book', gateP: 'You can browse without an account. To book and pay we need to know who you are. You earn points on every booking.', gateB: 'Log in or sign up', close: 'Keep browsing', points: 'Earn 40 points when you book on Glowly', back: 'Back' },
  pt: { search: 'Corte, cor, unhas…', sub: 'Perto · Qualquer dia', cut: 'Corte', nails: 'Unhas', color: 'Cor', skin: 'Pele', beard: 'Barba', near: 'Perto de você', book: 'Reservar horário', from: 'a partir de', services: 'Serviços', reviews: 'avaliações', like: 'Curtir', pass: 'Passar', empty: 'Você viu todas as promos de hoje', home: 'Início', map: 'Mapa', appts: 'Reservas', favs: 'Salvos', profile: 'Perfil', gateT: 'Entre para reservar', gateP: 'Você pode explorar sem conta. Para reservar e pagar precisamos saber quem você é. Você ganha pontos em cada reserva.', gateB: 'Entrar ou criar conta', close: 'Continuar explorando', points: 'Ganhe 40 pontos ao reservar no Glowly', back: 'Voltar' },
};
