export const PLANS = {
  basic: { price: 0, days: 60, bookings: 50 },
  pro: { price: 25 },
};
export const DAYS = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
export const PAYS = ['card', 'pse', 'nequi'];

export const tm = {
  es: {
    title: 'Registrá tu comercio', openPanel: 'Abrir panel del comercio', sub: 'Aparecé en el mapa de Glowlys y recibí reservas pagadas online. Sin comisiones por reserva.',
    steps: ['Datos', 'Horarios', 'Fotos y videos', 'Servicios', 'Cobros', 'Plan', 'Publicar'],
    step: 'Paso', of: 'de', next: 'Siguiente', back: 'Atrás', publish: 'Publicar mi comercio', edit: 'Editar',
    name: 'Nombre del comercio', cats: 'Categorías', desc: 'Descripción', descPh: 'Contá qué te hace distinto: estilo, equipo, experiencia…',
    address: 'Dirección', city: 'Ciudad', country: 'País', useLoc: 'Usar mi ubicación actual', locOk: 'Ubicación guardada',
    required: 'Completá nombre, al menos una categoría, dirección y ciudad.',
    cut: 'Corte', nails: 'Uñas', color: 'Color', skin: 'Piel', beard: 'Barba',
    days: { mon: 'Lunes', tue: 'Martes', wed: 'Miércoles', thu: 'Jueves', fri: 'Viernes', sat: 'Sábado', sun: 'Domingo' },
    open: 'Abierto', closed: 'Cerrado', from: 'Desde', to: 'Hasta',
    photos: 'Fotos del comercio', videos: 'Videos del comercio', addPhotos: 'Agregar fotos', addVideos: 'Agregar videos', remove: 'Quitar',
    mediaHint: 'Mostrá el local y tus trabajos. En esta demo los archivos no se guardan: se suben a Supabase en la etapa de backend.',
    svcTitle: 'Servicios', svcName: 'Nombre del servicio', svcMin: 'Duración (min)', svcPrice: 'Valor (USD)', svcDesc: 'Descripción', svcMedia: 'Foto o video (opcional)',
    addSvc: 'Agregar servicio', svcHint: 'El usuario ve el valor en su moneda y paga la reserva completa online.', svcNeed: 'Agregá al menos un servicio con nombre y valor.',
    payTitle: 'Medios de pago', payHint: 'Con qué podrán pagar los usuarios tu servicio dentro de la app.',
    card: 'Tarjeta de crédito / débito', pse: 'PSE (Colombia)', nequi: 'Nequi (Colombia)',
    accTitle: 'Cuenta donde recibís tus cobros', accHint: 'El alta la hace el proveedor de pagos en su propio formulario seguro: Glowlys no guarda números de cuenta ni de tarjeta.',
    accBtn: 'Conectar cuenta de cobros', accOk: 'Cuenta conectada (demo)', accNeed: 'Conectá tu cuenta de cobros para poder publicar.',
    planTitle: 'Elegí tu plan', planHint: 'Suscripción mensual fija. Sin comisiones por reserva ni por cliente nuevo.',
    basic: 'Básico', basicP: 'USD 0 · 60 días de prueba', basicL: ['Perfil en el marketplace', 'Agenda online', 'Hasta 50 reservas por mes', 'No incluye promociones'],
    pro: 'Pro', proP: 'USD 25 / mes', proL: ['Todo lo del Básico', 'Reservas ilimitadas', 'Promociones relámpago en el mapa', 'Micrositio con servicios, equipo y reseñas', 'Posicionamiento destacado', 'CRM, recordatorios por WhatsApp y tablero de ingresos'],
    rec: 'Recomendado', pick: 'Elegir',
    review: 'Revisá y publicá', preview: 'Así te ven los usuarios', summary: 'Resumen',
    done: '¡Tu comercio está listo!', doneP: 'Quedó guardado en esta demo. Cuando conectemos Supabase, tu perfil aparecerá en el mapa para todos los usuarios.',
    onlyDemo: 'Demo: los datos se guardan solo en este dispositivo.',
    from2: 'desde', photosN: 'fotos', videosN: 'videos', servicesN: 'servicios',
    needAccount: 'Creá tu cuenta de comercio para registrar tu negocio.', createAcc: 'Crear cuenta de comercio',
  },
  en: {
    title: 'Register your business', openPanel: 'Open business dashboard', sub: 'Show up on the Glowlys map and get bookings paid online. No per-booking commission.',
    steps: ['Details', 'Hours', 'Photos & videos', 'Services', 'Payouts', 'Plan', 'Publish'],
    step: 'Step', of: 'of', next: 'Next', back: 'Back', publish: 'Publish my business', edit: 'Edit',
    name: 'Business name', cats: 'Categories', desc: 'Description', descPh: 'What makes you different: style, team, experience…',
    address: 'Address', city: 'City', country: 'Country', useLoc: 'Use my current location', locOk: 'Location saved',
    required: 'Fill in the name, at least one category, address and city.',
    cut: 'Cut', nails: 'Nails', color: 'Color', skin: 'Skin', beard: 'Beard',
    days: { mon: 'Monday', tue: 'Tuesday', wed: 'Wednesday', thu: 'Thursday', fri: 'Friday', sat: 'Saturday', sun: 'Sunday' },
    open: 'Open', closed: 'Closed', from: 'From', to: 'To',
    photos: 'Business photos', videos: 'Business videos', addPhotos: 'Add photos', addVideos: 'Add videos', remove: 'Remove',
    mediaHint: 'Show your space and your work. In this demo files are not saved: they go to Supabase in the backend stage.',
    svcTitle: 'Services', svcName: 'Service name', svcMin: 'Duration (min)', svcPrice: 'Price (USD)', svcDesc: 'Description', svcMedia: 'Photo or video (optional)',
    addSvc: 'Add service', svcHint: 'Users see the price in their currency and pay the full booking online.', svcNeed: 'Add at least one service with a name and price.',
    payTitle: 'Payment methods', payHint: 'How users can pay for your service inside the app.',
    card: 'Credit / debit card', pse: 'PSE (Colombia)', nequi: 'Nequi (Colombia)',
    accTitle: 'Account where you receive payments', accHint: 'The payment provider handles sign-up in its own secure form: Glowlys never stores account or card numbers.',
    accBtn: 'Connect payout account', accOk: 'Account connected (demo)', accNeed: 'Connect your payout account to publish.',
    planTitle: 'Choose your plan', planHint: 'Fixed monthly subscription. No per-booking or new-client commission.',
    basic: 'Basic', basicP: 'USD 0 · 60-day trial', basicL: ['Marketplace profile', 'Online scheduling', 'Up to 50 bookings per month', 'Promotions not included'],
    pro: 'Pro', proP: 'USD 25 / month', proL: ['Everything in Basic', 'Unlimited bookings', 'Flash promotions on the map', 'Microsite with services, team and reviews', 'Featured placement', 'CRM, WhatsApp reminders and revenue dashboard'],
    rec: 'Recommended', pick: 'Choose',
    review: 'Review and publish', preview: 'How users see you', summary: 'Summary',
    done: 'Your business is ready!', doneP: 'Saved in this demo. Once Supabase is connected, your profile will appear on the map for all users.',
    onlyDemo: 'Demo: data is saved on this device only.',
    from2: 'from', photosN: 'photos', videosN: 'videos', servicesN: 'services',
    needAccount: 'Create your business account to register.', createAcc: 'Create business account',
  },
};
tm.pt = tm.es;
